descriptionFormat: ''
handle: test
hasDimensions: false
hasProductTitleField: true
hasVariantTitleField: false
hasVariants: false
name: Test
productFieldLayouts:
  8e52beb1-398a-4e13-a940-070086375cff:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\commerce\fieldlayoutelements\ProductTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
productTitleFormat: ''
siteSettings:
  04677986-61a7-4935-a707-cae0601cc8d5: # Craft Baukasten Sample
    hasUrls: false
    template: null
    uriFormat: null
  b2034624-b987-4407-828d-700fef161a67: # Test
    hasUrls: true
    template: ''
    uriFormat: 'test/{slug}'
skuFormat: ''
titleFormat: '{product.title}'
