field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7
fieldLayouts:
  37e695da-df19-4255-85fe-6b83ec641b29:
    tabs:
      -
        fields:
          51fb96cf-4339-4982-8328-b94b7530848e:
            required: false
            sortOrder: 5
          6475d0dc-d36f-464b-886b-0e49a2440722:
            required: false
            sortOrder: 3
          96e667df-51a4-4667-84b3-43e52090f6e6:
            required: true
            sortOrder: 1
          df558051-c14a-48af-b089-c5abc1bf066b:
            required: false
            sortOrder: 4
          f4b93567-1a28-444d-8e1e-cc42606a33e4:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  51fb96cf-4339-4982-8328-b94b7530848e:
    contentColumnType: string
    fieldGroup: null
    handle: width
    instructions: 'Has no effect if variant cover is selected'
    name: Width
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Wide
            -
              - value
              - w-wide
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - w-medium
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Narrow
            -
              - value
              - w-narrow
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  6475d0dc-d36f-464b-886b-0e49a2440722:
    contentColumnType: string
    fieldGroup: null
    handle: ratio
    instructions: ''
    name: Ratio
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Auto
            -
              - value
              - auto
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Landscape
            -
              - value
              - landscape
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Square
            -
              - value
              - square
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Portrait
            -
              - value
              - portrait
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  96e667df-51a4-4667-84b3-43e52090f6e6:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: true
    settings:
      allowSelfRelations: ''
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:1b735f91-a5f7-488b-9746-93d65fb4f211'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:1b735f91-a5f7-488b-9746-93d65fb4f211'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  df558051-c14a-48af-b089-c5abc1bf066b:
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: ''
    name: Variant
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Basic
            -
              - value
              - basic
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Cover
            -
              - value
              - cover
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f4b93567-1a28-444d-8e1e-cc42606a33e4:
    contentColumnType: boolean
    fieldGroup: null
    handle: caption
    instructions: ''
    name: Caption
    searchable: true
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: image
name: Image
sortOrder: 7
