field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7 # Builder: Content
fieldLayouts:
  913c40b7-d2b3-4cea-ac62-77ec2091aef2:
    tabs:
      -
        elements:
          -
            fieldUid: 8a0dc31d-c3e6-4205-ae27-67c8e3b3d256 # Images
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  8a0dc31d-c3e6-4205-ae27-67c8e3b3d256: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:1b735f91-a5f7-488b-9746-93d65fb4f211' # Images
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:1b735f91-a5f7-488b-9746-93d65fb4f211' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:1b735f91-a5f7-488b-9746-93d65fb4f211' # Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: true
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: bImageGallery
name: 'Image Gallery'
sortOrder: 8
