field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7 # Builder: Content
fieldLayouts:
  37e695da-df19-4255-85fe-6b83ec641b29:
    tabs:
      -
        elements:
          -
            fieldUid: 96e667df-51a4-4667-84b3-43e52090f6e6 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 6475d0dc-d36f-464b-886b-0e49a2440722 # Image Transform
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 51fb96cf-4339-4982-8328-b94b7530848e # Image Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: f4b93567-1a28-444d-8e1e-cc42606a33e4 # Show Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  51fb96cf-4339-4982-8328-b94b7530848e: # Image Width
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageWidth
    instructions: 'Has no effect if variant cover is selected'
    name: 'Image Width'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Wide
            -
              - value
              - wide
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Narrow
            -
              - value
              - narrow
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Cover
            -
              - value
              - cover
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Graphic
            -
              - value
              - graphic
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  96e667df-51a4-4667-84b3-43e52090f6e6: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:1b735f91-a5f7-488b-9746-93d65fb4f211' # Images
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:1b735f91-a5f7-488b-9746-93d65fb4f211' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  6475d0dc-d36f-464b-886b-0e49a2440722: # Image Transform
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageTransform
    instructions: ''
    name: 'Image Transform'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Auto
            -
              - value
              - auto
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Landscape
            -
              - value
              - landscape
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Square
            -
              - value
              - square
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Portrait
            -
              - value
              - portrait
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f4b93567-1a28-444d-8e1e-cc42606a33e4: # Show Image Caption
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: showImageCaption
    instructions: ''
    name: 'Show Image Caption'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: bImage
name: Image
sortOrder: 5
