field: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
fieldLayouts:
  410c9682-a3f7-4475-9013-0453aac4635d:
    tabs:
      -
        elements:
          -
            fieldUid: be45c3e2-5e9f-491e-a000-94d95c4fa20b # Snippet
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 727b44a7-8246-484f-9861-87f2ded3cdbf
            warning: null
            width: 100
          -
            fieldUid: 9cb7ea0d-8dd4-4298-ac6c-ab6c0efbe6ba # Snippet Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5894475-806c-4ca8-b23c-509f0c4fd7e7
            warning: null
            width: 100
          -
            fieldUid: e6857cd6-fc09-4396-93bd-3a9fc9011446 # Snippet Language
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4cf3d5fe-3e7c-4b78-943a-3434d46aa2cb
            warning: null
            width: 100
          -
            fieldUid: cf5b11e3-a6d6-430f-991f-9b78f9e4dd7f # Open
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abccd044-3e6d-4f0e-b792-937722131014
            warning: null
            width: 100
        name: Content
        uid: c033e8a9-eab3-4bd0-bea5-4a8d2dcf5ad3
fields:
  9cb7ea0d-8dd4-4298-ac6c-ab6c0efbe6ba: # Snippet Name
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: snippetName
    instructions: null
    name: 'Snippet Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  be45c3e2-5e9f-491e-a000-94d95c4fa20b: # Snippet
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: snippet
    instructions: null
    name: Snippet
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: true
      columnType: null
      initialRows: 4
      multiline: true
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  cf5b11e3-a6d6-430f-991f-9b78f9e4dd7f: # Open
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: open
    instructions: null
    name: Open
    searchable: false
    settings:
      default: true
      offLabel: Closed
      onLabel: Open
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  e6857cd6-fc09-4396-93bd-3a9fc9011446: # Snippet Language
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: snippetLanguage
    instructions: null
    name: 'Snippet Language'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - HTML
            -
              - value
              - html
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Twig
            -
              - value
              - twig
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - JavaScript
            -
              - value
              - javascript
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - CSS
            -
              - value
              - css
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Scss
            -
              - value
              - scss
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Bash
            -
              - value
              - bash
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Markdown
            -
              - value
              - markdown
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - JSON
            -
              - value
              - json
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - PHP
            -
              - value
              - php
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: blockCode
name: Code
sortOrder: 13
