field: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
fieldLayouts:
  2f43cd1f-4b91-4b38-aa35-4ae90d08f2db:
    tabs:
      -
        elements:
          -
            fieldUid: 0a686d89-8754-4f00-a79e-fed75548909d # Images
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4078acc8-f5db-408e-87f7-59f4c72eba2b
            warning: null
            width: 100
          -
            fieldUid: 1a64748f-2870-4c18-a869-f2b050ede5ba # Image Transform
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 259e8250-4463-4fa6-8745-a8c5c15887c9
            warning: null
            width: 100
        name: Content
        uid: 075e2dcc-f0cc-4f2d-b89b-d427b1f479ef
fields:
  0a686d89-8754-4f00-a79e-fed75548909d: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:6c5fc0dd-cf56-48d8-8af8-88abe763b970' # Files
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      source: null
      sources:
        - 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
      targetSiteId: null
      validateRelatedElements: true
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  1a64748f-2870-4c18-a869-f2b050ede5ba: # Image Transform
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageTransform
    instructions: null
    name: 'Image Transform'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Landscape
            -
              - value
              - landscape
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Square
            -
              - value
              - square
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Portrait
            -
              - value
              - portrait
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Auto
            -
              - value
              - auto
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: blockImageSlider
name: 'Image Slider'
sortOrder: 9
