field: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
fieldLayouts:
  6c449cd7-ebc2-4ce6-be61-1e8c90cb176b:
    tabs:
      -
        elements:
          -
            fieldUid: 75195ab8-b7c4-4dca-b807-ef8a042ef5a9 # Images
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d20dac90-4c46-4c75-8a7b-6a20e8db72d4
            warning: null
            width: 50
          -
            fieldUid: 62883121-63a2-4e5c-a6f3-4855cf64df2c # Image Transform
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6299a8e5-46d9-498c-8a62-af502549e574
            warning: null
            width: 50
          -
            fieldUid: df1d53fb-d9ed-4066-93e5-a46aac3f458e # Image Columns
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff8d7aa6-ec14-4f00-9239-6766a144a11c
            warning: null
            width: 50
          -
            fieldUid: e0e9e510-46ff-45aa-aa46-700b325bb911 # Show Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1ac5c10-3219-412e-9541-d662f4db2e68
            warning: null
            width: 50
        name: Content
        uid: 56042e3e-7a7b-4a4c-9222-63e004682c9b
fields:
  75195ab8-b7c4-4dca-b807-ef8a042ef5a9: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: null
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:6c5fc0dd-cf56-48d8-8af8-88abe763b970' # Files
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      source: null
      sources:
        - 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
      targetSiteId: null
      validateRelatedElements: true
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  62883121-63a2-4e5c-a6f3-4855cf64df2c: # Image Transform
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageTransform
    instructions: null
    name: 'Image Transform'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Landscape
            -
              - value
              - landscape
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Square
            -
              - value
              - square
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Portrait
            -
              - value
              - portrait
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Auto
            -
              - value
              - auto
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  df1d53fb-d9ed-4066-93e5-a46aac3f458e: # Image Columns
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageColumns
    instructions: null
    name: 'Image Columns'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - '2'
            -
              - value
              - '2'
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - '3'
            -
              - value
              - '3'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  e0e9e510-46ff-45aa-aa46-700b325bb911: # Show Image Caption
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: showImageCaption
    instructions: null
    name: 'Show Image Caption'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: blockImageGrid
name: 'Image Grid'
sortOrder: 6
