field: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
fieldLayouts:
  58ddc97d-9694-4104-a136-b6344987e1b6:
    tabs:
      -
        elements:
          -
            fieldUid: 35b67fb3-4bdb-470f-a686-3d46c5cd5f96 # Image
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 33352127-ae4e-4ffd-8ccc-28940f642a9b
            warning: null
            width: 50
          -
            fieldUid: 70bc887b-faf2-45c7-b4bc-4299acd343da # Image Transform
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 80d0e43a-19da-4d09-949d-05a033560bec
            warning: null
            width: 50
          -
            fieldUid: 9b73b533-898f-4f77-a500-37ea0be0afc7 # Show Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7d1dd14d-4f69-4907-85f3-46d5d1d5df4f
            warning: null
            width: 50
          -
            fieldUid: 1be86da8-5273-40c6-ba88-718f5c32a6c3 # Image Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 230907db-2ae4-4386-80ec-2f05e9fb64f3
            warning: null
            width: 50
        name: Content
        uid: 5e8a312e-45d0-491c-924d-84d96af3b270
fields:
  1be86da8-5273-40c6-ba88-718f5c32a6c3: # Image Width
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageWidth
    instructions: null
    name: 'Image Width'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Wide
            -
              - value
              - wide
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Narrow
            -
              - value
              - narrow
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  9b73b533-898f-4f77-a500-37ea0be0afc7: # Show Image Caption
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: showImageCaption
    instructions: null
    name: 'Show Image Caption'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  35b67fb3-4bdb-470f-a686-3d46c5cd5f96: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:6c5fc0dd-cf56-48d8-8af8-88abe763b970' # Files
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      source: null
      sources:
        - 'volume:f1b38495-8096-48fa-9b78-0da345e3295c' # Images
      targetSiteId: null
      validateRelatedElements: true
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  70bc887b-faf2-45c7-b4bc-4299acd343da: # Image Transform
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageTransform
    instructions: null
    name: 'Image Transform'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Landscape
            -
              - value
              - landscape
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Square
            -
              - value
              - square
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Portrait
            -
              - value
              - portrait
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Auto
            -
              - value
              - auto
            -
              - default
              - '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: blockImage
name: Image
sortOrder: 5
