field: 74eb36ae-7a26-4e7d-b454-990ec52617f0 # Builder: Content
fieldLayouts:
  4d1ff7c7-65c5-415d-8314-672e427848a1:
    tabs:
      -
        elements:
          -
            fieldUid: b48826ad-7083-4a54-8082-52ede1c340b7 # Video ID
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a2484323-15c1-4358-a188-d18a600c5958 # Autoplay
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: e55876f6-9fe1-448f-b0bb-320990caabee # Loop
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
fields:
  a2484323-15c1-4358-a188-d18a600c5958: # Autoplay
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: autoplay
    instructions: ''
    name: Autoplay
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  b48826ad-7083-4a54-8082-52ede1c340b7: # Video ID
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: videoId
    instructions: ''
    name: 'Video ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e55876f6-9fe1-448f-b0bb-320990caabee: # Loop
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: loop
    instructions: ''
    name: Loop
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: bYoutubeVideo
name: 'Youtube Video'
sortOrder: 9
