field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7 # Page Builder
fieldLayouts:
  2d1a2077-0f3e-4574-996a-7694d2d4dd5f:
    tabs:
      -
        elements:
          -
            fieldUid: 75831d9f-5f4b-4d1f-8e79-62b4ddbd4654 # Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 630ace10-7ffc-4363-8a28-81d660b49f2c # Padding Vertical
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 374c97da-fa09-458e-bf13-c75c7cebeafd # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  374c97da-fa09-458e-bf13-c75c7cebeafd: # Background Color
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: ''
    name: 'Background Color'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Transparent
            -
              - value
              - bg-transparent
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - bg-white
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Black
            -
              - value
              - bg-black
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  630ace10-7ffc-4363-8a28-81d660b49f2c: # Padding Vertical
    contentColumnType: string
    fieldGroup: null
    handle: paddingVertical
    instructions: ''
    name: 'Padding Vertical'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - py-0--fluid
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'Factor 1'
            -
              - value
              - py-1--fluid
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Factor 2'
            -
              - value
              - py-2--fluid
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Factor 3'
            -
              - value
              - py-3--fluid
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Factor 4'
            -
              - value
              - py-4--fluid
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Factor 5'
            -
              - value
              - py-5--fluid
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  75831d9f-5f4b-4d1f-8e79-62b4ddbd4654: # Width
    contentColumnType: string
    fieldGroup: null
    handle: width
    instructions: ''
    name: Width
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Content
            -
              - value
              - content
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Full
            -
              - value
              - full
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: cbSection
name: Section
sortOrder: 2
