field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7
fieldLayouts:
  a955a0c4-3cfe-41e5-b5a0-15822c2c92c5:
    tabs:
      -
        fields:
          2e1bb75e-94e1-43e5-84d6-c4781444b1ff:
            required: true
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  2e1bb75e-94e1-43e5-84d6-c4781444b1ff:
    contentColumnType: text
    fieldGroup: null
    handle: richText
    instructions: ''
    name: 'Rich Text'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Baukasten.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: richText
name: 'Rich Text'
sortOrder: 4
