field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7
fieldLayouts:
  1a2943cd-204b-408f-a5f4-03f0a63cfc4e:
    tabs:
      -
        fields:
          3e915132-407a-4154-ba2d-9dbf4f869a8d:
            required: true
            sortOrder: 1
          5c305a98-30bb-466c-bf84-bdae3fdf804d:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  3e915132-407a-4154-ba2d-9dbf4f869a8d:
    contentColumnType: text
    fieldGroup: null
    handle: snippet
    instructions: ''
    name: Snippet
    searchable: true
    settings:
      mode: gfm
    translationKeyFormat: null
    translationMethod: none
    type: luwes\codemirror\fields\CodeMirrorField
  5c305a98-30bb-466c-bf84-bdae3fdf804d:
    contentColumnType: string
    fieldGroup: null
    handle: language
    instructions: ''
    name: Language
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Bash
            -
              - value
              - bash
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - CSS
            -
              - value
              - css
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - HTML
            -
              - value
              - html
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - JS
            -
              - value
              - js
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - JSON
            -
              - value
              - json
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Markdown
            -
              - value
              - markdown
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - PHP
            -
              - value
              - php
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Scss
            -
              - value
              - scss
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - TXT
            -
              - value
              - txt
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Twig
            -
              - value
              - twig
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Vue
            -
              - value
              - vue
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: codeSnippet
name: 'Code Snippet'
sortOrder: 12
