field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7 # Page Builder
fieldLayouts:
  1a2943cd-204b-408f-a5f4-03f0a63cfc4e:
    tabs:
      -
        elements:
          -
            fieldUid: 3e915132-407a-4154-ba2d-9dbf4f869a8d # Snippet
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5c305a98-30bb-466c-bf84-bdae3fdf804d # Snippet Language
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3e915132-407a-4154-ba2d-9dbf4f869a8d: # Snippet
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: snippet
    instructions: ''
    name: Snippet
    searchable: true
    settings:
      errorMessage: 'Unable to find component class ''luwes\codemirror\fields\CodeMirrorField''.'
      expectedType: luwes\codemirror\fields\CodeMirrorField
      settings: '{"mode":"gfm"}'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MissingField
  5c305a98-30bb-466c-bf84-bdae3fdf804d: # Snippet Language
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: snippetLanguage
    instructions: ''
    name: 'Snippet Language'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Bash
            -
              - value
              - bash
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - CSS
            -
              - value
              - css
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - HTML
            -
              - value
              - html
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - JS
            -
              - value
              - js
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - JSON
            -
              - value
              - json
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Markdown
            -
              - value
              - markdown
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - PHP
            -
              - value
              - php
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Scss
            -
              - value
              - scss
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - TXT
            -
              - value
              - txt
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Twig
            -
              - value
              - twig
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Vue
            -
              - value
              - vue
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: codeSnippet
name: 'Code Snippet'
sortOrder: 12
