field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7 # Page Builder
fieldLayouts:
  d10b1e97-bff7-4616-9232-1fca2b376a59:
    tabs:
      -
        elements:
          -
            fieldUid: 49d2cd4b-66d9-49e6-b274-8a67c9ea630a # Definition List
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  49d2cd4b-66d9-49e6-b274-8a67c9ea630a: # Definition List
    contentColumnType: string
    fieldGroup: null
    handle: definitionList
    instructions: ''
    name: 'Definition List'
    searchable: true
    settings:
      columns:
        __assoc__:
          -
            - f56216a6-8623-42ab-b812-b10971f828e6 # Term
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - b4623113-f388-41e1-8610-19812a5433f0 # Description
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_6_definitionlist}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
handle: definitionList
name: 'Definition List'
sortOrder: 6
