field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7 # Page Builder
fieldLayouts:
  a927dffc-4caa-4e9f-9440-32eec896d193:
    tabs:
      -
        elements:
          -
            fieldUid: 0b3ac2de-d0c7-49a5-af9c-0704a584918f # Forms
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0b3ac2de-d0c7-49a5-af9c-0704a584918f: # Forms
    contentColumnType: string
    fieldGroup: null
    handle: forms
    instructions: ''
    name: Forms
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: true
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: verbb\formie\fields\Forms
handle: forms
name: Forms
sortOrder: 14
