field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7
fieldLayouts:
  a927dffc-4caa-4e9f-9440-32eec896d193:
    tabs:
      -
        elements:
          -
            fieldUid: 0b3ac2de-d0c7-49a5-af9c-0704a584918f
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0b3ac2de-d0c7-49a5-af9c-0704a584918f:
    contentColumnType: string
    fieldGroup: null
    handle: freeform
    instructions: ''
    name: Freeform
    searchable: false
    settings:
      errorMessage: 'Unable to find component class ''Solspace\Freeform\FieldTypes\FormFieldType''.'
      expectedType: Solspace\Freeform\FieldTypes\FormFieldType
      settings: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MissingField
handle: freeform
name: Freeform
sortOrder: 14
