field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7
fieldLayouts:
  a927dffc-4caa-4e9f-9440-32eec896d193:
    tabs:
      -
        fields:
          0b3ac2de-d0c7-49a5-af9c-0704a584918f:
            required: true
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  0b3ac2de-d0c7-49a5-af9c-0704a584918f:
    contentColumnType: integer
    fieldGroup: null
    handle: freeform
    instructions: ''
    name: Freeform
    searchable: false
    translationKeyFormat: null
    translationMethod: none
    type: Solspace\Freeform\FieldTypes\FormFieldType
handle: freeform
name: Freeform
sortOrder: 14
