field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7 # Page Builder
fieldLayouts:
  dae92868-9408-4630-822b-ed58b0a46705:
    tabs:
      -
        elements:
          -
            fieldUid: be80d133-f849-4cdf-86c9-92a64b304fce # Headline
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f10f3f3f-0dde-4a21-9489-e5579e814469 # Size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 354a9e1a-6a46-4212-ac49-b6c48d7d93b3 # Visual Size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  354a9e1a-6a46-4212-ac49-b6c48d7d93b3: # Visual Size
    contentColumnType: string
    fieldGroup: null
    handle: visualSize
    instructions: ''
    name: 'Visual Size'
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Inherit
            -
              - value
              - ''
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - 'MS 1'
            -
              - value
              - ms-1
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'MS 2'
            -
              - value
              - ms-2
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'MS 3'
            -
              - value
              - ms-3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'MS 4'
            -
              - value
              - ms-4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'MS 5'
            -
              - value
              - ms-5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'MS 6'
            -
              - value
              - ms-6
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  be80d133-f849-4cdf-86c9-92a64b304fce: # Headline
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f10f3f3f-0dde-4a21-9489-e5579e814469: # Size
    contentColumnType: string
    fieldGroup: null
    handle: size
    instructions: ''
    name: Size
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - H2
            -
              - value
              - h2
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - H3
            -
              - value
              - h3
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - H4
            -
              - value
              - h4
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - H5
            -
              - value
              - h5
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - H6
            -
              - value
              - h6
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: headline
name: Headline
sortOrder: 3
