field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7 # Builder: Content
fieldLayouts:
  441f24a0-9da9-4bab-8b4d-9120085a06bc:
    tabs:
      -
        elements:
          -
            fieldUid: 0874e231-9cb3-4e41-a637-e9c7bd453b9c # Images
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 19b81a5c-df1a-47ce-96d8-eb6f06c2c442 # Image Columns
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 130712c6-6ae4-4ddd-991c-39f51eb115f4 # Show Image Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  19b81a5c-df1a-47ce-96d8-eb6f06c2c442: # Image Columns
    columnSuffix: eqvhcqia
    contentColumnType: string
    fieldGroup: null
    handle: imageColumns
    instructions: ''
    name: 'Image Columns'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - '2'
            -
              - value
              - '2'
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - '3'
            -
              - value
              - '3'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  0874e231-9cb3-4e41-a637-e9c7bd453b9c: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Images
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:1b735f91-a5f7-488b-9746-93d65fb4f211' # Images
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: true
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:3f1e1a84-bf8f-4543-b3a8-4c210f0d244a' # Files
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:1b735f91-a5f7-488b-9746-93d65fb4f211' # Images
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: true
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  130712c6-6ae4-4ddd-991c-39f51eb115f4: # Show Image Caption
    columnSuffix: mvhxakdr
    contentColumnType: boolean
    fieldGroup: null
    handle: showImageCaption
    instructions: ''
    name: 'Show Image Caption'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: imageGridCalculated
name: 'Image Grid Calculated'
sortOrder: 7
