field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7 # Page Builder
fieldLayouts:
  1ba1f2b9-3953-4131-89da-28c4ab8fb9a2:
    tabs:
      -
        elements:
          -
            fieldUid: 13c17c81-9eb9-42c8-a656-3f03051d91ff # Images
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e112cf13-2c4f-4604-89f8-48dd867dbba6 # Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5f0bc252-87f4-4239-9928-86063fd664a3 # Columns
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5dcb3824-f538-4f5c-81c6-2fcd6b6bd38c # Ratio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5dcb3824-f538-4f5c-81c6-2fcd6b6bd38c: # Ratio
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: ratio
    instructions: ''
    name: Ratio
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Portrait
            -
              - value
              - portrait
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Lanscape
            -
              - value
              - lanscape
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Square
            -
              - value
              - square
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Auto
            -
              - value
              - auto
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  5f0bc252-87f4-4239-9928-86063fd664a3: # Columns
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: columns
    instructions: ''
    name: Columns
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - '2'
            -
              - value
              - c-2
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - '3'
            -
              - value
              - c-3
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  13c17c81-9eb9-42c8-a656-3f03051d91ff: # Images
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Images
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:1b735f91-a5f7-488b-9746-93d65fb4f211' # Images
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:1b735f91-a5f7-488b-9746-93d65fb4f211' # Images
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  e112cf13-2c4f-4604-89f8-48dd867dbba6: # Caption
    columnSuffix: null
    contentColumnType: boolean
    fieldGroup: null
    handle: caption
    instructions: ''
    name: Caption
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: imageGrid
name: 'Image Grid'
sortOrder: 8
