field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7
fieldLayouts:
  913c40b7-d2b3-4cea-ac62-77ec2091aef2:
    tabs:
      -
        fields:
          8a0dc31d-c3e6-4205-ae27-67c8e3b3d256:
            required: true
            sortOrder: 1
          b512cbc9-6c77-4ffd-9963-9cca00e3307a:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  8a0dc31d-c3e6-4205-ae27-67c8e3b3d256:
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Images
    searchable: true
    settings:
      allowSelfRelations: ''
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:1b735f91-a5f7-488b-9746-93d65fb4f211'
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:1b735f91-a5f7-488b-9746-93d65fb4f211'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b512cbc9-6c77-4ffd-9963-9cca00e3307a:
    contentColumnType: string
    fieldGroup: null
    handle: ratio
    instructions: ''
    name: Ratio
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Square
            -
              - value
              - square
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Landscape
            -
              - value
              - landscape
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Portrait
            -
              - value
              - portrait
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Auto
            -
              - value
              - auto
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: imageGallery
name: 'Image Gallery'
sortOrder: 9
