field: d3a65ce7-395f-4a98-bbf8-24dd3bca3dab
fieldLayouts:
  409d7e43-197f-4c1a-b575-1bc10104083f:
    tabs:
      -
        fields:
          7354821a-d150-4ef1-a15c-4a8db7b7425e:
            required: false
            sortOrder: 2
          b8310612-27cd-4485-9500-f2d695b32bd6:
            required: true
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  7354821a-d150-4ef1-a15c-4a8db7b7425e:
    contentColumnType: string
    fieldGroup: null
    handle: ratio
    instructions: ''
    name: Ratio
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Auto
            -
              - value
              - auto
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Landscape
            -
              - value
              - landscape
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Portrait
            -
              - value
              - portrait
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Square
            -
              - value
              - square
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  b8310612-27cd-4485-9500-f2d695b32bd6:
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: ''
    name: Images
    searchable: false
    settings:
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:1b735f91-a5f7-488b-9746-93d65fb4f211'
      defaultUploadLocationSubpath: ''
      limit: '2'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:1b735f91-a5f7-488b-9746-93d65fb4f211'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: '1'
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: imageImage
name: 'Image : Image'
sortOrder: 5
