field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7 # Page Builder
fieldLayouts:
  de564934-874a-4504-b99d-3ba8f0aa0684:
    tabs:
      -
        elements:
          -
            fieldUid: f18642d1-7028-4990-b411-92357c537720 # Quote
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8015ed9c-f053-44a1-a982-c8543fecb850 # Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 432cc329-7587-408d-8b61-a70b7bfd7520 # Source Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  432cc329-7587-408d-8b61-a70b7bfd7520: # Source Url
    contentColumnType: string(255)
    fieldGroup: null
    handle: sourceUrl
    instructions: ''
    name: 'Source Url'
    searchable: true
    settings:
      maxLength: '255'
      placeholder: ''
      types:
        - url
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Url
  8015ed9c-f053-44a1-a982-c8543fecb850: # Source
    contentColumnType: text
    fieldGroup: null
    handle: source
    instructions: ''
    name: Source
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f18642d1-7028-4990-b411-92357c537720: # Quote
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: quote
name: Quote
sortOrder: 5
