field: d3a65ce7-395f-4a98-bbf8-24dd3bca3dab # Content Builder
fieldLayouts:
  c5511cec-4e00-49d5-926f-39cae0bd599e:
    tabs:
      -
        elements:
          -
            fieldUid: 2f08af3c-3397-43c7-8bc2-8f24b32950c6 # Quote
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 268ba3e9-f256-4a48-ad61-c554a80ed66f # Quoter
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2f08af3c-3397-43c7-8bc2-8f24b32950c6: # Quote
    contentColumnType: text
    fieldGroup: null
    handle: quote
    instructions: ''
    name: Quote
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: '1'
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  268ba3e9-f256-4a48-ad61-c554a80ed66f: # Quoter
    contentColumnType: text
    fieldGroup: null
    handle: quoter
    instructions: ''
    name: Quoter
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: quote
name: Quote
sortOrder: 3
