field: 8ea6300e-c7ee-4655-8226-8ad9f0725531
fieldLayouts:
  a9bacecd-8da7-4e4a-9b59-c617e85e19d2:
    tabs:
      -
        fields:
          23db484d-0a47-41ce-b7f2-5011966c10f8:
            required: false
            sortOrder: 5
          33f318a2-52b4-444f-8e60-6b503ae78d61:
            required: false
            sortOrder: 1
          3e777533-2154-477b-8503-378b99e9f317:
            required: false
            sortOrder: 3
          43fe1a37-497c-4cde-b26d-a26a388cbf21:
            required: false
            sortOrder: 7
          4594ea1a-c7db-4124-b517-235e69fbb221:
            required: false
            sortOrder: 2
          97baf93d-a4ad-43a8-b6f1-969db71997b3:
            required: false
            sortOrder: 4
          c08dacfe-dd95-4b81-ae41-700318af6bd4:
            required: false
            sortOrder: 6
        name: Content
        sortOrder: 1
fields:
  23db484d-0a47-41ce-b7f2-5011966c10f8:
    contentColumnType: boolean
    fieldGroup: null
    handle: snippetDefaultState
    instructions: ''
    name: 'Snippet Default State'
    searchable: true
    settings:
      default: '1'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  33f318a2-52b4-444f-8e60-6b503ae78d61:
    contentColumnType: boolean
    fieldGroup: null
    handle: isActive
    instructions: ''
    name: 'Is Active'
    searchable: true
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  3e777533-2154-477b-8503-378b99e9f317:
    contentColumnType: text
    fieldGroup: null
    handle: snippetDescription
    instructions: ''
    name: 'Snippet Description'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  43fe1a37-497c-4cde-b26d-a26a388cbf21:
    contentColumnType: string
    fieldGroup: null
    handle: snippetPurpose
    instructions: ''
    name: 'Snippet Purpose'
    searchable: true
    settings:
      multi: true
      options:
        -
          __assoc__:
            -
              - label
              - Necessary
            -
              - value
              - necessary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Statistics
            -
              - value
              - statistics
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'External Media'
            -
              - value
              - externalMedia
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Live Chat'
            -
              - value
              - liveChat
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Advertisement
            -
              - value
              - advertisement
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Checkboxes
  4594ea1a-c7db-4124-b517-235e69fbb221:
    contentColumnType: text
    fieldGroup: null
    handle: snippetName
    instructions: ''
    name: 'Snippet Name'
    searchable: true
    settings:
      charLimit: ''
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  97baf93d-a4ad-43a8-b6f1-969db71997b3:
    contentColumnType: text
    fieldGroup: null
    handle: snippetCode
    instructions: ''
    name: 'Snippet Code'
    searchable: true
    settings:
      mode: javascript
    translationKeyFormat: null
    translationMethod: none
    type: luwes\codemirror\fields\CodeMirrorField
  c08dacfe-dd95-4b81-ae41-700318af6bd4:
    contentColumnType: boolean
    fieldGroup: null
    handle: snippetRequired
    instructions: ''
    name: 'Snippet Required'
    searchable: true
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: snippet
name: Snippet
sortOrder: 1
