field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7
fieldLayouts:
  4716487a-dd77-4c80-ae4c-e1d6a4b12f20:
    tabs:
      -
        fields:
          ae553cfa-0516-497a-903a-b1ebc1e1aec7:
            required: false
            sortOrder: 2
          cec3f3ec-7aeb-4c61-ba7c-c70bb53ba989:
            required: true
            sortOrder: 1
          f0f50d91-0322-4b0c-9d12-c88c8dd152fa:
            required: false
            sortOrder: 3
        name: Content
        sortOrder: 1
fields:
  ae553cfa-0516-497a-903a-b1ebc1e1aec7:
    contentColumnType: boolean
    fieldGroup: null
    handle: autoplay
    instructions: ''
    name: Autoplay
    searchable: true
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  cec3f3ec-7aeb-4c61-ba7c-c70bb53ba989:
    contentColumnType: text
    fieldGroup: null
    handle: videoId
    instructions: ''
    name: 'Video ID'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f0f50d91-0322-4b0c-9d12-c88c8dd152fa:
    contentColumnType: boolean
    fieldGroup: null
    handle: loop
    instructions: ''
    name: Loop
    searchable: true
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: youtubeVideo
name: 'Youtube Video'
sortOrder: 11
