field: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7 # Page Builder
fieldLayouts:
  4716487a-dd77-4c80-ae4c-e1d6a4b12f20:
    tabs:
      -
        elements:
          -
            fieldUid: cec3f3ec-7aeb-4c61-ba7c-c70bb53ba989 # Video ID
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ae553cfa-0516-497a-903a-b1ebc1e1aec7 # Autoplay
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f0f50d91-0322-4b0c-9d12-c88c8dd152fa # Loop
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  ae553cfa-0516-497a-903a-b1ebc1e1aec7: # Autoplay
    contentColumnType: boolean
    fieldGroup: null
    handle: autoplay
    instructions: ''
    name: Autoplay
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  cec3f3ec-7aeb-4c61-ba7c-c70bb53ba989: # Video ID
    contentColumnType: text
    fieldGroup: null
    handle: videoId
    instructions: ''
    name: 'Video ID'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f0f50d91-0322-4b0c-9d12-c88c8dd152fa: # Loop
    contentColumnType: boolean
    fieldGroup: null
    handle: loop
    instructions: ''
    name: Loop
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: youtubeVideo
name: 'Youtube Video'
sortOrder: 11
