fieldLayouts:
  d25723b9-65cc-43f0-8155-e90ba334d210:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: ''
            label: ''
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 0170a444-b2ac-4ff6-b81f-fd8712ecdfb7
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: pageBuilder
hasTitleField: true
name: 'Page Builder'
section: 66b60a7f-6d8d-4931-af03-e6878a97d4fe
sortOrder: 2
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
