fieldLayouts:
  64b63849-8292-493e-8f6b-0baf76887a87:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 3dc41ab0-2a40-40b1-a265-106c542fe89b
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Default
        sortOrder: 1
handle: demopage
hasTitleField: false
name: Home
section: 2bb2c616-10f1-4d48-96ad-a33312d55c5c
sortOrder: 1
titleFormat: '{section.name|raw}'
