fieldLayouts:
  506f0b17-eda4-4046-8a22-bd23939c3ad8:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: d3a65ce7-395f-4a98-bbf8-24dd3bca3dab
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
handle: contentBuilder
hasTitleField: true
name: 'Content Builder'
section: 66b60a7f-6d8d-4931-af03-e6878a97d4fe
sortOrder: 3
titleFormat: ''
