fieldLayouts:
  64b63849-8292-493e-8f6b-0baf76887a87:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: ''
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 3dc41ab0-2a40-40b1-a265-106c542fe89b # Rich Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Default
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 9270bb9a-a35a-4ccf-b8c5-d4ed81fa621d
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Vizy
        sortOrder: 2
handle: demopage
hasTitleField: false
name: Home
section: 2bb2c616-10f1-4d48-96ad-a33312d55c5c # Home
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
