fieldLayouts:
  1d64a453-d02e-4117-abb2-ac8f622f81b5:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Entry
        sortOrder: 1
handle: error
hasTitleField: true
name: Error
section: 6d7978f4-a806-4644-942f-ee03828ff3b9 # Error Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
