fieldLayouts:
  033dfae7-ba48-4593-be29-b9ee4814ab4e:
    tabs:
      -
        fields:
          0807cf36-9d29-4810-9a89-3ca325a0ec6d:
            required: false
            sortOrder: 2
          8022c412-08db-4075-8549-b0aeb7093b15:
            required: false
            sortOrder: 1
          d3f43b9c-3c3e-4aa1-afeb-d2ba5afbe114:
            required: false
            sortOrder: 4
          e9f13c1d-0525-4ecc-bf67-f927e561a2c8:
            required: false
            sortOrder: 3
        name: Content
        sortOrder: 1
handle: images
hasUrls: true
name: Images
settings:
  path: '@assetsUrl/images/'
sortOrder: 2
type: craft\volumes\Local
url: '@webroot/assets/images/'
