fieldLayouts:
  b7ec31a2-48bd-439f-a3f7-12beb57e1a2a:
    tabs:
      -
        fields:
          0807cf36-9d29-4810-9a89-3ca325a0ec6d:
            required: false
            sortOrder: 2
          8022c412-08db-4075-8549-b0aeb7093b15:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
handle: files
hasUrls: false
name: Files
settings:
  path: '@assetsUrl/files/'
sortOrder: 1
type: craft\volumes\Local
url: '@webroot/assets/files/'
