fieldLayouts:
  26b1a67a-65fc-472e-ab94-f8a8469bc119:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
          -
            fieldUid: 8022c412-08db-4075-8549-b0aeb7093b15 # Asset Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 57d146c5-f3f6-4b1e-a598-cca8b7e18537 # Asset Alt Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0807cf36-9d29-4810-9a89-3ca325a0ec6d # Asset Caption
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e9f13c1d-0525-4ecc-bf67-f927e561a2c8 # Asset Source
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d3f43b9c-3c3e-4aa1-afeb-d2ba5afbe114 # Asset Source Url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: users
hasUrls: true
name: Users
settings:
  path: '@webroot/assets/users/'
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: craft\volumes\Local
url: '@assetsUrl/users/'
