fieldLayouts:
  26b1a67a-65fc-472e-ab94-f8a8469bc119:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: users
hasUrls: true
name: Users
settings:
  path: '@webroot/assets/users/'
sortOrder: 4
type: craft\volumes\Local
url: '@assetsUrl/users/'
