contentColumnType: text
fieldGroup: abd97710-319a-43e1-aa96-b717f022025c
handle: assetSource
instructions: ''
name: 'Asset Source'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
