columnSuffix: qroeaicj
contentColumnType: text
fieldGroup: abd97710-319a-43e1-aa96-b717f022025c # Assets
handle: assetAltText
instructions: ''
name: 'Asset Alt Text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
