contentColumnType: string
fieldGroup: a22d2fcb-a200-45ff-bf8c-29d48187a063 # Builders
handle: contentBuilder
instructions: ''
name: 'Content Builder'
searchable: true
settings:
  contentTable: '{{%matrixcontent_contentbuilder}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
