contentColumnType: string(255)
fieldGroup: abd97710-319a-43e1-aa96-b717f022025c
handle: assetSourceUrl
instructions: ''
name: 'Asset Source Url'
searchable: true
settings:
  maxLength: '255'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
