columnSuffix: null
contentColumnType: string
fieldGroup: b141ca14-c1e0-41ee-9607-3a8030f5faca # Entry
handle: entryImage
instructions: ''
name: 'Entry: Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:1b735f91-a5f7-488b-9746-93d65fb4f211' # Images
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: true
  showUnpermittedFiles: true
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:3f1e1a84-bf8f-4543-b3a8-4c210f0d244a' # Files
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:3f1e1a84-bf8f-4543-b3a8-4c210f0d244a' # Files
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: true
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
