columnSuffix: qbkvinot
contentColumnType: string(560)
fieldGroup: b141ca14-c1e0-41ee-9607-3a8030f5faca # Entry
handle: entryShortDescription
instructions: ''
name: 'Entry: Short Description'
searchable: true
settings:
  byteLimit: null
  charLimit: 140
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
