columnSuffix: wfhvutqc
contentColumnType: text
fieldGroup: b141ca14-c1e0-41ee-9607-3a8030f5faca # Entry
handle: entryCustomTitle
instructions: ''
name: 'Entry: Custom Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
