columnSuffix: azaqxrxw
contentColumnType: text
fieldGroup: b141ca14-c1e0-41ee-9607-3a8030f5faca # Entry
handle: entrySEO
instructions: ''
name: 'Entry: SEO'
searchable: false
settings:
  elementDisplayPreviewType: google
  facebookTabEnabled: ''
  generalEnabledFields:
    - seoPreview
    - mainEntityOfPage
    - seoTitle
    - seoDescription
    - seoKeywords
    - seoImage
    - robots
    - canonicalUrl
  generalTabEnabled: '1'
  sitemapTabEnabled: ''
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
