contentColumnType: string
fieldGroup: 8a51cd55-1898-4755-b1ea-9d4bbc87d521
handle: klaroSnippets
instructions: ''
name: 'Klaro Snippets'
searchable: true
settings:
  contentTable: '{{%matrixcontent_klarosnippets}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
