columnSuffix: null
contentColumnType: string
fieldGroup: a22d2fcb-a200-45ff-bf8c-29d48187a063 # Builders
handle: pageBuilder
instructions: ''
name: 'Page Builder'
searchable: true
settings:
  contentTable: '{{%matrixcontent_pagebuilder}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
