columnSuffix: mfwquxzo
contentColumnType: string
fieldGroup: 7ef31d75-a55b-40a3-ad93-058ae8faa950 # Vizy
handle: vizyBlockSettingsTableType
instructions: ''
name: 'Vizy Block Settings Table Type'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - 'First Row as Headline'
        -
          - value
          - firstRowAsHeadline
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - 'First Column as Headline'
        -
          - value
          - firstColumnAsHeadline
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'First Row & Column as Headlines'
        -
          - value
          - firstRowColumnAsHeadlines
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
