columnSuffix: null
contentColumnType: string
fieldGroup: 7ef31d75-a55b-40a3-ad93-058ae8faa950 # Vizy
handle: vizyBlockTwoTextCols
instructions: ''
name: 'Vizy Block Two Text Cols'
searchable: false
settings:
  columns:
    __assoc__:
      -
        - 90d090e4-d70d-4588-a2dc-7aba845e81cf
        -
          __assoc__:
            -
              - width
              - ''
      -
        - f541cbdf-068b-4159-b956-db6056d52ba4
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_vizyblocktwotextcols}}'
  fieldLayout: table
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: '1'
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
