columnSuffix: null
contentColumnType: string
fieldGroup: 7ef31d75-a55b-40a3-ad93-058ae8faa950 # Vizy
handle: vizyFieldEntries
instructions: ''
name: 'Vizy Field Entries'
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: null
  sources:
    - 'section:77aac30e-d20c-4034-ae0e-8833d1ca136c' # Articles
    - 'section:66b60a7f-6d8d-4931-af03-e6878a97d4fe' # Pages
    - singles
  targetSiteId: null
  validateRelatedElements: true
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
