columnSuffix: gpbcrrjv
contentColumnType: text
fieldGroup: 7ef31d75-a55b-40a3-ad93-058ae8faa950 # Vizy
handle: vizyFieldTable
instructions: ''
name: 'Vizy Field Table'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'Col 1'
            -
              - handle
              - tableCol1
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col2
        -
          __assoc__:
            -
              - heading
              - 'Col 2'
            -
              - handle
              - tableCol2
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col3
        -
          __assoc__:
            -
              - heading
              - 'Col 3'
            -
              - handle
              - tableCol3
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col4
        -
          __assoc__:
            -
              - heading
              - 'Col 4'
            -
              - handle
              - tableCol4
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col5
        -
          __assoc__:
            -
              - heading
              - 'Col 5'
            -
              - handle
              - tableCol5
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col6
        -
          __assoc__:
            -
              - heading
              - 'Col 6'
            -
              - handle
              - tableCol6
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
        -
          - col2
          - ''
        -
          - col3
          - ''
        -
          - col4
          - ''
        -
          - col5
          - ''
        -
          - col6
          - ''
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
