columnSuffix: pwlaixrq
contentColumnType: text
fieldGroup: 7ef31d75-a55b-40a3-ad93-058ae8faa950 # Vizy
handle: vizyFieldMinimal
instructions: ''
name: 'Vizy Field Minimal'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes:
    - 3f1e1a84-bf8f-4543-b3a8-4c210f0d244a
    - 1b735f91-a5f7-488b-9746-93d65fb4f211
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: "{\r\n    \"buttons\": [\"html\", \"formatting\", \"h1\", \"h2\", \"h3\", \"h4\", \"h5\", \"h6\", \"bold\", \"italic\", \"underline\", \"strike\", \"ordered-list\", \"unordered-list\", \"code-block\", \"hr\", \"highlight\", \"align-left\", \"align-right\", \"align-center\", \"align-justify\", \"clear-format\", \"line-break\", \"link\", \"image\", \"undo\", \"redo\"],\r\n    \"formatting\": [\"paragraph\", \"code\", \"blockquote\", \"h1\", \"h2\", \"h3\", \"h4\", \"h5\", \"h6\"],\r\n    \"toolbarFixed\": true\r\n}"
  showUnpermittedFiles: '1'
  showUnpermittedVolumes: '1'
  trimEmptyParagraphs: '1'
  vizyConfig: Minimal.json
translationKeyFormat: null
translationMethod: none
type: verbb\vizy\fields\VizyField
