columnSuffix: tunouvdd
contentColumnType: string
fieldGroup: 7ef31d75-a55b-40a3-ad93-058ae8faa950 # Vizy
handle: vizyBlockSettingsTextImageRatio
instructions: ''
name: 'Vizy Block Settings Text Image Ratio'
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - '1:1'
        -
          - value
          - 1-1
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '2:1'
        -
          - value
          - 2-1
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - '3:1'
        -
          - value
          - 3-1
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\RadioButtons
