columnSuffix: lmnwmlee
contentColumnType: boolean
fieldGroup: 7ef31d75-a55b-40a3-ad93-058ae8faa950 # Vizy
handle: vizyBlockSettingsTextImagePosition
instructions: ''
name: 'Vizy Block Settings Text Image Position'
searchable: false
settings:
  default: false
  offLabel: 'Image Right'
  onLabel: 'Image Left'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
