columnSuffix: kjstnvmf
contentColumnType: text
fieldGroup: 7ef31d75-a55b-40a3-ad93-058ae8faa950 # Vizy
handle: vizyStandard
instructions: ''
name: 'Vizy Field Standard'
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  manualConfig: ''
  showUnpermittedFiles: ''
  showUnpermittedVolumes: ''
  trimEmptyParagraphs: '1'
  vizyConfig: Standard.json
translationKeyFormat: null
translationMethod: none
type: verbb\vizy\fields\VizyField
