columnSuffix: kuhrkiib
contentColumnType: string
fieldGroup: 7ef31d75-a55b-40a3-ad93-058ae8faa950 # Vizy
handle: vizyBlockSettingsImageRatio
instructions: ''
name: 'Vizy Block Settings Image Ratio'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Landscape
        -
          - value
          - landscape
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Square
        -
          - value
          - square
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Portrait
        -
          - value
          - portrait
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Auto
        -
          - value
          - auto
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
