columnSuffix: xlspfxeo
contentColumnType: text
fieldGroup: 7ef31d75-a55b-40a3-ad93-058ae8faa950 # Vizy
handle: vizyBuilder
instructions: ''
name: 'Vizy Builder'
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  columnType: text
  configSelectionMode: choose
  defaultTransform: ''
  fieldData:
    -
      __assoc__:
        -
          - id
          - group-HClKasAiyZ
        -
          - name
          - 'MIXED CONTENT'
        -
          - blockTypes
          -
            -
              __assoc__:
                0:
                  - id
                  - type-r5E2Tp31uI
                1:
                  - name
                  - 'Text : Image'
                2:
                  - handle
                  - textImage
                3:
                  - icon
                  -
                    __assoc__:
                      -
                        - label
                        - Columns
                      -
                        - value
                        - columns-solid
                5:
                  - enabled
                  - true
                6:
                  - layoutUid
                  - 5a8fbda1-d5c9-4d4e-be97-7db638316196
                7:
                  - layoutConfig
                  -
                    __assoc__:
                      -
                        - tabs
                        -
                          -
                            __assoc__:
                              -
                                - name
                                - Content
                              -
                                - sortOrder
                                - 1
                              -
                                - elements
                                -
                                  -
                                    __assoc__:
                                      0: [type, craft\fieldlayoutelements\CustomField]
                                      1: [label, '']
                                      2: [instructions, '']
                                      5: [required, '1']
                                      6: [width, 100]
                                      7: [fieldUid, 18c56e54-c014-411c-b44f-5c09d4637a15] # Vizy Field Image
                                  -
                                    __assoc__:
                                      - [type, craft\fieldlayoutelements\HorizontalRule]
                                  -
                                    __assoc__:
                                      0: [type, craft\fieldlayoutelements\CustomField]
                                      5: [required, false]
                                      6: [width, 50]
                                      7: [fieldUid, f4280cbc-3a04-4a3e-8619-608c7b4f00e5] # Vizy Block Settings Image Ratio
                                  -
                                    __assoc__:
                                      0: [type, craft\fieldlayoutelements\CustomField]
                                      5: [required, false]
                                      6: [width, 50]
                                      7: [fieldUid, 868835d4-14ae-4c80-bd52-9454f51e8e97] # Vizy Block Settings Text Image Position
                                  -
                                    __assoc__:
                                      - [type, craft\fieldlayoutelements\HorizontalRule]
                                  -
                                    __assoc__:
                                      0: [type, craft\fieldlayoutelements\CustomField]
                                      1: [label, '']
                                      2: [instructions, '']
                                      5: [required, '1']
                                      6: [width, 100]
                                      7: [fieldUid, 7612e1e2-a329-48e0-9508-17c146c77d76] # Vizy Field Standard
    -
      __assoc__:
        -
          - id
          - group-krSwHLREEa
        -
          - name
          - 'Text Content'
        -
          - blockTypes
          -
            -
              __assoc__:
                0:
                  - id
                  - type-hWplVo1W8C
                1:
                  - name
                  - 'Text : Text'
                2:
                  - handle
                  - textText
                3:
                  - icon
                  -
                    __assoc__:
                      -
                        - label
                        - Columns
                      -
                        - value
                        - columns-solid
                5:
                  - enabled
                  - true
                6:
                  - layoutUid
                  - 189103e8-a2c0-46aa-b7d9-6f3e244f43e2
                7:
                  - layoutConfig
                  -
                    __assoc__:
                      -
                        - tabs
                        -
                          -
                            __assoc__:
                              -
                                - name
                                - Content
                              -
                                - sortOrder
                                - 1
                              -
                                - elements
                                -
                                  -
                                    __assoc__:
                                      0: [type, craft\fieldlayoutelements\CustomField]
                                      5: [required, false]
                                      6: [width, 100]
                                      7: [fieldUid, 7443db2c-3177-41fd-b1cb-07be6d679ef7] # Vizy Block Two Text Cols
    -
      __assoc__:
        -
          - id
          - group-JbYFqeLbem
        -
          - name
          - 'Inline Builder'
        -
          - blockTypes
          -
            -
              __assoc__:
                0:
                  - id
                  - type-XB7W6NvSrD
                1:
                  - name
                  - Test
                2:
                  - handle
                  - test
                3:
                  - icon
                  -
                    __assoc__:
                      -
                        - label
                        - Buffer
                      -
                        - value
                        - buffer-brands
                5:
                  - enabled
                  - true
                6:
                  - layoutUid
                  - 0a0e8db4-7b09-4f3f-867c-eff2a2462357
                7:
                  - layoutConfig
                  -
                    __assoc__:
                      -
                        - tabs
                        -
                          -
                            __assoc__:
                              -
                                - name
                                - Content
                              -
                                - sortOrder
                                - 1
                              -
                                - elements
                                -
                                  -
                                    __assoc__:
                                      0: [type, craft\fieldlayoutelements\CustomField]
                                      5: [required, false]
                                      6: [width, 100]
                                      7: [fieldUid, 97e382ff-495d-448a-842b-d4e74e2509bf] # Vizy Block Fancy
  manualConfig: ''
  showUnpermittedFiles: ''
  showUnpermittedVolumes: ''
  trimEmptyParagraphs: '1'
  vizyConfig: Standard.json
translationKeyFormat: null
translationMethod: none
type: verbb\vizy\fields\VizyField
