columnSuffix: null
contentColumnType: string
fieldGroup: 7ef31d75-a55b-40a3-ad93-058ae8faa950 # Vizy
handle: vizyBlockFancy
instructions: ''
name: 'Vizy Block Fancy'
searchable: false
settings:
  columns:
    __assoc__:
      -
        - 7074ed07-0282-465c-847a-0cd7804c6e3e # Image
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 25d23745-7283-42b9-9e4d-57e893e77056 # Vizy Builder
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_vizyblockfancy}}'
  fieldLayout: table
  maxRows: ''
  minRows: ''
  placeholderKey: null
  propagationMethod: all
  selectionLabel: ''
  staticField: '1'
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
