field: 49d2cd4b-66d9-49e6-b274-8a67c9ea630a
fieldLayouts:
  718ef18f-9fcf-4a94-b811-faa5b0902fbe:
    tabs:
      -
        fields:
          b4623113-f388-41e1-8610-19812a5433f0:
            required: false
            sortOrder: 2
          f56216a6-8623-42ab-b812-b10971f828e6:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  b4623113-f388-41e1-8610-19812a5433f0:
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Baukasten.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  f56216a6-8623-42ab-b812-b10971f828e6:
    contentColumnType: text
    fieldGroup: null
    handle: term
    instructions: ''
    name: Term
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Baukasten.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
