field: 171fade2-74bd-4677-b8af-53699003dc44 # Buttons
fieldLayouts:
  b9bb2ac2-02e3-48c8-bde1-682fb8d46a45:
    tabs:
      -
        elements:
          -
            fieldUid: 4afe7728-65d2-48c1-80f7-aeafcf978ff6 # Button
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 85fef928-9fd5-4b9b-a7c5-73976952425b # Variant
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4afe7728-65d2-48c1-80f7-aeafcf978ff6: # Button
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: button
    instructions: ''
    name: Button
    searchable: true
    settings:
      errorMessage: 'Unable to find component class ''fruitstudios\linkit\fields\LinkitField''.'
      expectedType: fruitstudios\linkit\fields\LinkitField
      settings: '{"allowCustomText":"1","allowTarget":"1","defaultText":"","selectLinkText":"","types":{"fruitstudios\\linkit\\models\\Email":{"enabled":"1","customLabel":"","customPlaceholder":""},"fruitstudios\\linkit\\models\\Phone":{"enabled":"","customLabel":"","customPlaceholder":""},"fruitstudios\\linkit\\models\\Url":{"enabled":"1","customLabel":"","customPlaceholder":"","allowAlias":"","allowMailto":"","allowHash":"1","allowPaths":""},"fruitstudios\\linkit\\models\\Twitter":{"enabled":"","customLabel":"","customPlaceholder":""},"fruitstudios\\linkit\\models\\Facebook":{"enabled":"","customLabel":"","customPlaceholder":""},"fruitstudios\\linkit\\models\\Instagram":{"enabled":"","customLabel":"","customPlaceholder":""},"fruitstudios\\linkit\\models\\LinkedIn":{"enabled":"","customLabel":"","customPlaceholder":""},"fruitstudios\\linkit\\models\\Entry":{"enabled":"1","customLabel":"","sources":"*","customSelectionLabel":""},"fruitstudios\\linkit\\models\\Category":{"enabled":"1","customLabel":"","sources":"*","customSelectionLabel":""},"fruitstudios\\linkit\\models\\Asset":{"enabled":"","customLabel":"","sources":"*","customSelectionLabel":""},"fruitstudios\\linkit\\models\\User":{"enabled":"","customLabel":"","sources":"*","customSelectionLabel":"","userPath":""}}}'
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MissingField
  85fef928-9fd5-4b9b-a7c5-73976952425b: # Variant
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: variant
    instructions: ''
    name: Variant
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - primary
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - secondary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Ghost
            -
              - value
              - ghost
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Outlined
            -
              - value
              - outlined
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
