field: 7443db2c-3177-41fd-b1cb-07be6d679ef7 # Vizy Block Two Text Cols
fieldLayouts:
  fa3202bc-41ee-4e98-88f0-6e1aa7ad3734:
    tabs:
      -
        elements:
          -
            fieldUid: 90d090e4-d70d-4588-a2dc-7aba845e81cf
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f541cbdf-068b-4159-b956-db6056d52ba4
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  90d090e4-d70d-4588-a2dc-7aba845e81cf:
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: textCol1
    instructions: ''
    name: 'Text Col 1'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      showUnpermittedFiles: ''
      showUnpermittedVolumes: ''
      trimEmptyParagraphs: '1'
      vizyConfig: Minimal.json
    translationKeyFormat: null
    translationMethod: none
    type: verbb\vizy\fields\VizyField
  f541cbdf-068b-4159-b956-db6056d52ba4:
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: textCol2
    instructions: ''
    name: 'Text Col 2'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      showUnpermittedFiles: ''
      showUnpermittedVolumes: ''
      trimEmptyParagraphs: '1'
      vizyConfig: Minimal.json
    translationKeyFormat: null
    translationMethod: none
    type: verbb\vizy\fields\VizyField
