fieldLayouts:
  3da9685d-8dbf-48ce-95ab-6081a48668c0:
    tabs:
      -
        fields:
          8ea6300e-c7ee-4655-8226-8ad9f0725531:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
handle: klaroSnippets
name: 'Klaro Snippets'
