enableVersioning: false
handle: home
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  04677986-61a7-4935-a707-cae0601cc8d5: # Craft Baukasten Sample
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
