enableVersioning: false
handle: navigationMain
name: 'Navigation Main'
propagationMethod: all
siteSettings:
  04677986-61a7-4935-a707-cae0601cc8d5: # Craft Baukasten Sample
    enabledByDefault: false
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 2
  uid: 6e12a140-52a6-4ca8-a569-22eb6133f09c
type: structure
