enableVersioning: true
handle: pages
name: Pages
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  04677986-61a7-4935-a707-cae0601cc8d5:
    enabledByDefault: false
    hasUrls: true
    template: _entry
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 755bdacc-e4ff-4ce3-9ce9-8dcfc719ccc7
type: structure
